//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBaseApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class HotelClientBaseEntities : DbContext
    {
        private static HotelClientBaseEntities _context;
        public HotelClientBaseEntities()
            : base("name=HotelClientBaseEntities")
        {
        }

        public static HotelClientBaseEntities GetContext()
        {
            if (_context == null) 
                _context = new HotelClientBaseEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Аренда> Аренда { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Номера> Номера { get; set; }
        public virtual DbSet<Отель> Отель { get; set; }
    }
}
