//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBaseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аренда
    {
        public int Код_Аренды { get; set; }
        public int Код_Номера { get; set; }
        public int Код_Клиента { get; set; }
        public int Код_Отеля { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Номера Номера { get; set; }
        public virtual Отель Отель { get; set; }
    }
}
